@KafkaFlowProducer_HostAddress = https://localhost:7104

GET {{KafkaFlowProducer_HostAddress}}/api/todos/
Accept: application/json

###
DELETE /api/todos/
Accept: application/json

### add todo 1
POST {{KafkaFlowProducer_HostAddress}}/api/todos
Content-Type: application/json
Accept: application/json

{
  "Id": 1,
  "Title": "Title :)",
  "Description": "Description :)",
  "DueDate": "2021-12-01"
}

### add random work todo
POST {{KafkaFlowProducer_HostAddress}}/api/todos/work
Content-Type: application/json
Accept: application/json

{
  "Title": "Title Work",
  "Description": "Work your but off asshole2!",
  "DueDate": "2025-12-02"
}

### add random training todo
POST {{KafkaFlowProducer_HostAddress}}/api/todos/training
Content-Type: application/json
Accept: application/json

{
  "Title": "Title Training",
  "Description": "Training your brain man2!",
  "DueDate": "2025-12-02"
}
